CREATE TABLE users (
	user_id VARCHAR(255) NOT NULL,
	nickname VARCHAR(255) NULL DEFAULT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY (user_id) USING BTREE
) charset = utf8;

CREATE TABLE words (
	word_id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description TEXT NULL DEFAULT NULL,
	writer_id VARCHAR(255) NOT NULL,
	viewcount INT NULL DEFAULT 0,
	likes INT NULL DEFAULT 0,
	written_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (word_id) USING BTREE
) charset = utf8;

CREATE TABLE likes (
	id INT NOT NULL AUTO_INCREMENT,
	word_id INT NOT NULL,
	user_id varchar(255) NOT NULL,
	PRIMARY KEY (id) USING BTREE
);
 
ALTER DATABASE springmvcdb DEFAULT CHARACTER SET utf8 ;

